import React from "react";
import { createRoot } from "react-dom/client";
import "./styles.css";
import RosterGrouping from "./RosterGrouping";

type Project = { id:string; class_name:string; school_year:string; group_count:number; student_count?:number };
type PreviewRow = { student_number:string; name:string; group_number:string; is_leader:boolean };
type Student = PreviewRow & { id:string };
type Period = { id:string; name:string; start_date:string; expected_end_date:string; status:string; result_version:number };
type Paper = { id:string; sheet_number:number; status:string; front_status:string; back_status:string };
type Run = { id:string; original_filename:string; page_index:number; status:string; side?:string; quality?:any; version_conflict?:boolean };
const terminal = ["completed", "failed", "cancelled"];
const sideReady = (status:string) => ["reviewed", "confirmed_blank", "posted"].includes(status);

function App() {
  const [csrf, setCsrf] = React.useState("");
  const [message, setMessage] = React.useState("正在连接本地服务…");
  const [projects, setProjects] = React.useState<Project[]>([]);
  const [selected, setSelected] = React.useState("");
  const [project, setProject] = React.useState({ class_name:"二四一五班", school_year:"2026—2027", group_count:7 });
  const [csv, setCsv] = React.useState("学号,姓名,组号,是否组长\n1,张三,1,是\n2,李四,1,否");
  const [previewRows, setPreviewRows] = React.useState<PreviewRow[]>([]);
  const [students, setStudents] = React.useState<Student[]>([]);
  const [frontRules, setFrontRules] = React.useState("作业＋,5\n课堂＋,5\n成绩＋,5\n服务＋,5\n值日＋,5\n活动＋,5\n其他＋,5");
  const [backRules, setBackRules] = React.useState("作业－,-5\n课堂－,-5\n值日－,-5\n迟到－,-5\n晚归－,-5\n其他－,-5");
  const [periodForm, setPeriodForm] = React.useState({ name:"第1—2周", start_date:"2026-09-01", expected_end_date:"2026-09-14" });
  const [periods, setPeriods] = React.useState<Period[]>([]);
  const [periodId, setPeriodId] = React.useState("");
  const [papers, setPapers] = React.useState<Paper[]>([]);
  const [scanFiles, setScanFiles] = React.useState<File[]>([]);
  const [jobs, setJobs] = React.useState<any[]>([]);
  const [runs, setRuns] = React.useState<Run[]>([]);
  const [review, setReview] = React.useState<any>(null);
  const [results, setResults] = React.useState<any>(null);
  const [scorepackFile, setScorepackFile] = React.useState<File | null>(null);
  const deepLinkLoaded = React.useRef(false);
  const currentPeriod = periods.find(item => item.id === periodId);
  const currentProject = projects.find(item => item.id === selected);

  const reloadProjects = () => fetch("/api/projects").then(r => r.json()).then(setProjects);
  const loadPeriods = async (projectId = selected) => { if (!projectId) return []; const rows = await fetch(`/api/projects/${projectId}/periods`).then(r => r.json()); setPeriods(rows); return rows as Period[]; };
  const loadPapers = async (id = periodId) => { if (id) setPapers(await fetch(`/api/periods/${id}/papers`).then(r => r.json())); };
  const loadRuns = async () => { if (selected) setRuns(await fetch(`/api/projects/${selected}/recognition-runs`).then(r => r.json())); };
  const loadResults = async (id = periodId) => { if (id) setResults(await fetch(`/api/periods/${id}/results`).then(r => r.json())); };
  const post = async (url:string, body:unknown) => { const r = await fetch(url, { method:"POST", headers:{ "content-type":"application/json", "x-scoreflow-csrf":csrf }, body:JSON.stringify(body) }); const data = await r.json().catch(() => ({})); if (!r.ok) throw new Error(data.detail || "操作失败"); return data; };
  const act = async (work:() => Promise<void>) => { try { await work(); } catch (error) { setMessage(error instanceof Error ? error.message : "操作失败"); } };

  React.useEffect(() => { fetch("/api/session").then(r => r.ok ? r.json() : Promise.reject()).then(data => { setCsrf(data.csrf_token); setMessage("本地数据已就绪"); return reloadProjects(); }).catch(() => setMessage("请通过 ScoreFlow 启动器打开本页面")); }, []);
  React.useEffect(() => { if (!jobs.some(job => !terminal.includes(job.status))) return; const timer = window.setInterval(async () => { const updated = await Promise.all(jobs.map(job => fetch(`/api/scan-jobs/${job.id}`).then(r => r.json()))); setJobs(updated); if (updated.every(job => terminal.includes(job.status))) await loadRuns(); }, 700); return () => window.clearInterval(timer); }, [jobs, selected]);
  React.useEffect(() => { const handler = (event:KeyboardEvent) => { if (!review || event.target instanceof HTMLInputElement || event.target instanceof HTMLTextAreaElement) return; const current = review.observations.find((item:any) => !item.manual_class && item.auto_class === "review"); const mapping:any = { "1":"blank", "2":"slash_forward", "3":"slash_back", "4":"x" }; if (current && mapping[event.key]) { event.preventDefault(); decide(current.slot_id, mapping[event.key]); } }; window.addEventListener("keydown", handler); return () => window.removeEventListener("keydown", handler); }, [review]);

  const chooseProject = async (id:string) => {
    setSelected(id); setPeriodId(""); setPeriods([]); setPapers([]); setResults(null); setPreviewRows([]); setRuns([]);
    if (!id) { setStudents([]); return; }
    const [rules, roster] = await Promise.all([fetch(`/api/projects/${id}/rules`).then(r => r.json()), fetch(`/api/projects/${id}/students`).then(r => r.json())]);
    setStudents(roster);
    setFrontRules(rules.filter((r:any) => r.side === "front" && r.is_active).map((r:any) => `${r.name},${r.unit_score}`).join("\n"));
    setBackRules(rules.filter((r:any) => r.side === "back" && r.is_active).map((r:any) => `${r.name},${r.unit_score}`).join("\n"));
    await loadPeriods(id);
    setRuns(await fetch(`/api/projects/${id}/recognition-runs`).then(r => r.json()));
  };
  const choosePeriod = async (item:Period) => { setPeriodId(item.id); setPeriodForm({ name:item.name, start_date:item.start_date, expected_end_date:item.expected_end_date }); await Promise.all([loadPapers(item.id), loadResults(item.id)]); };
  React.useEffect(() => { if (!csrf || deepLinkLoaded.current) return; const query = new URLSearchParams(window.location.search); const projectId = query.get("project"); const targetPeriod = query.get("period"); if (!projectId) return; deepLinkLoaded.current = true; void act(async () => { await chooseProject(projectId); if (targetPeriod) { const rows = await fetch(`/api/projects/${projectId}/periods`).then(r => r.json()) as Period[]; const item = rows.find(row => row.id === targetPeriod); if (item) await choosePeriod(item); } }); }, [csrf]);
  const parseRules = (text:string, side:"front"|"back") => text.split("\n").filter(Boolean).map(line => { const [name, score] = line.split(","); return { name:name.trim(), side, unit_score:Number(score) }; });
  const savePeriod = async () => {
    if (currentPeriod?.status === "draft") { const r = await fetch(`/api/periods/${periodId}`, { method:"PUT", headers:{ "content-type":"application/json", "x-scoreflow-csrf":csrf }, body:JSON.stringify(periodForm) }); if (!r.ok) throw new Error((await r.json()).detail); setMessage("周期草稿已更新"); }
    else { const created = await post(`/api/projects/${selected}/periods`, periodForm); setPeriodId(created.id); setMessage("周期草稿已建立"); }
    await loadPeriods();
  };
  const uploadScans = async () => { const form = new FormData(); scanFiles.forEach(file => form.append("files", file)); const r = await fetch(`/api/projects/${selected}/scans`, { method:"POST", headers:{ "x-scoreflow-csrf":csrf }, body:form }); const data = await r.json(); if (!r.ok) throw new Error(data.detail); setJobs(data.items.map((item:any) => ({ id:item.job_id, status:item.duplicate ? "completed" : "queued", stage:item.duplicate ? "重复文件" : "等待处理", completed_pages:0, total_pages:0 }))); setMessage("扫描文件已进入本地处理队列"); };
  const openReview = async (id:string) => setReview(await fetch(`/api/recognition-runs/${id}`).then(r => r.json()));
  const decide = async (slot:string, value:string) => { const r = await fetch(`/api/recognition-runs/${review.id}/review`, { method:"PUT", headers:{ "content-type":"application/json", "x-scoreflow-csrf":csrf }, body:JSON.stringify({ decisions:{ [slot]:value } }) }); if (!r.ok) throw new Error((await r.json()).detail); await openReview(review.id); };
  const identify = async (run:Run) => { const code = window.prompt("请输入纸表右上方短编号"); if (!code) return; const side = window.prompt("请输入面别：front（正面）或 back（背面）"); if (side !== "front" && side !== "back") throw new Error("面别必须是 front 或 back"); await post(`/api/recognition-runs/${run.id}/identity`, { sheet_id:code, side }); await loadRuns(); };
  const addNote = async () => { const text = window.prompt("输入纸面备注的简短电子记录（可留空不录）"); if (!text) return; await post(`/api/recognition-runs/${review.id}/notes`, { note_text:text }); await openReview(review.id); };
  const cancelJob = async (id:string) => { await post(`/api/scan-jobs/${id}/cancel`, {}); setJobs(jobs.map(job => job.id === id ? { ...job, stage:"正在取消" } : job)); setMessage("已请求取消扫描任务"); };
  const withdrawBlank = async (sheetId:string, side:"front"|"back") => { const reason = window.prompt("请输入撤回空白确认的原因"); if (!reason) return; await post(`/api/papers/${sheetId}/withdraw-blank`, { side, reason }); await loadPapers(); setMessage("空白确认已撤回"); };
  const reversePaper = async (sheetId:string) => { const reason = window.prompt("请输入整表撤销入账原因"); if (!reason) return; await post(`/api/papers/${sheetId}/reverse`, { reason, idempotency_key:crypto.randomUUID() }); await Promise.all([loadPapers(), loadResults()]); setMessage("已生成关联反向流水，原记录没有被删除"); };
  const createReport = async (variant:"teacher"|"display", draft:boolean) => { const report = await post(`/api/periods/${periodId}/reports`, { variant, draft }); window.open(report.download_url, "_blank"); setMessage(report.is_draft ? "已生成带水印的未结算草稿" : "已生成正式周期报告"); };
  const exportProject = async () => { const result = await post(`/api/projects/${selected}/scorepack`, {}); window.location.href = result.download_url; setMessage("完整项目包已生成并开始下载"); };
  const restoreProject = async () => { if (!scorepackFile) return; const form = new FormData(); form.append("package", scorepackFile); const response = await fetch("/api/scorepacks/restore", { method:"POST", headers:{ "x-scoreflow-csrf":csrf }, body:form }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.detail || "项目包恢复失败"); await reloadProjects(); await chooseProject(data.project.id); setScorepackFile(null); setMessage(`已恢复独立项目：${data.project.class_name}`); };

  return <main>
    <header><div className="eyebrow">班级积分 · 本地工具</div><h1>ScoreFlow</h1><p className="lead">纸上登记，扫描复核，可靠入账。</p><p><span className="dot"/>{message}</p></header>
    <div className="grid">
      <section><h2>1. 建立班级</h2><label>班级名称<input value={project.class_name} onChange={e => setProject({ ...project, class_name:e.target.value })}/></label><label>学年<input value={project.school_year} onChange={e => setProject({ ...project, school_year:e.target.value })}/></label><label>小组数量<input type="number" min="1" max="20" value={project.group_count} onChange={e => setProject({ ...project, group_count:Number(e.target.value) })}/></label><button disabled={!csrf} onClick={() => act(async () => { const created = await post("/api/projects", project); await reloadProjects(); await chooseProject(created.id); setMessage("班级已建立，可导入名单"); })}>建立班级</button></section>
      <section><h2>选择班级 / 高级 CSV 导入</h2><label>选择班级<select value={selected} onChange={e => act(() => chooseProject(e.target.value))}><option value="">请选择</option>{projects.map(item => <option key={item.id} value={item.id}>{item.class_name} · {item.group_count}组 · {item.student_count ?? 0}人</option>)}</select></label><details><summary>使用旧版四列 CSV</summary><label>CSV（学号、姓名、组号、是否组长）<textarea rows={6} value={csv} onChange={e => setCsv(e.target.value)}/></label><div className="actions"><button disabled={!selected} onClick={() => act(async () => { const data = await post(`/api/projects/${selected}/students/preview`, { csv_text:csv }); setPreviewRows(data.rows); setMessage(`CSV预检通过：${data.count} 名学生`); })}>只预检</button><button disabled={!selected || !previewRows.length} onClick={() => act(async () => { const data = await post(`/api/projects/${selected}/students/import`, { csv_text:csv }); await reloadProjects(); await chooseProject(selected); setMessage(`已完整导入 ${data.imported} 名学生`); })}>确认导入</button></div></details></section>
      <section><h2>3. 周期设置</h2><label>周期显示名<input value={periodForm.name} onChange={e => setPeriodForm({ ...periodForm, name:e.target.value })}/><small>例如：第3周、第3—4周</small></label><label>开始日期<input type="date" value={periodForm.start_date} onChange={e => setPeriodForm({ ...periodForm, start_date:e.target.value })}/></label><label>预计结束<input type="date" value={periodForm.expected_end_date} onChange={e => setPeriodForm({ ...periodForm, expected_end_date:e.target.value })}/></label><div className="actions"><button disabled={!selected} onClick={() => act(savePeriod)}>{currentPeriod?.status === "draft" ? "更新草稿" : "新建周期草稿"}</button>{periodId && <button onClick={() => { setPeriodId(""); setPapers([]); setResults(null); }}>清空选择</button>}</div></section>
      <section><h2>4. 积分规则</h2><label>正面项目（名称,分值）<textarea rows={7} value={frontRules} onChange={e => setFrontRules(e.target.value)}/></label><label>背面项目（名称,分值）<textarea rows={6} value={backRules} onChange={e => setBackRules(e.target.value)}/></label><button disabled={!selected} onClick={() => act(async () => { const rules = [...parseRules(frontRules, "front"), ...parseRules(backRules, "back")]; const r = await fetch(`/api/projects/${selected}/rules`, { method:"PUT", headers:{ "content-type":"application/json", "x-scoreflow-csrf":csrf }, body:JSON.stringify(rules) }); if (!r.ok) throw new Error((await r.json()).detail); setMessage("规则已保存，将用于下一个开始的周期"); })}>保存规则</button></section>
      <section><h2>5. 完整备份与跨电脑恢复</h2><p>项目包包含数据库快照、纸表、原始扫描、校正证据及报告。恢复会建立独立项目，不覆盖同名身份。</p><button disabled={!selected} onClick={() => act(exportProject)}>导出 .scorepack</button><label>恢复项目包<input type="file" accept=".scorepack" onChange={e => setScorepackFile(e.target.files?.[0] || null)}/></label><button disabled={!scorepackFile} onClick={() => act(restoreProject)}>校验并恢复为独立项目</button></section>
      <section><h2>安全退出</h2><p>退出会先请求扫描任务在安全页边界停止，再关闭数据库和本地服务。只关闭浏览器标签不会退出。</p><button className="danger" disabled={!csrf} onClick={() => act(async () => { await post("/api/app/quit", {}); setMessage("ScoreFlow 正在安全退出，可以关闭此页面"); })}>退出 ScoreFlow</button></section>
    </div>

    <RosterGrouping projectId={selected} periodId={periodId} groupCount={currentProject?.group_count || 7} csrf={csrf} onMessage={setMessage} onRosterChanged={async () => { await reloadProjects(); if (selected) { setStudents(await fetch(`/api/projects/${selected}/students`).then(r => r.json())); await loadPeriods(selected); } }}/>

    {periods.length > 0 && <section className="preview"><h2>周期列表</h2><table><thead><tr><th>周期</th><th>日期</th><th>状态</th><th>结果版本</th><th></th></tr></thead><tbody>{periods.map(item => <tr key={item.id}><td>{item.name}</td><td>{item.start_date} 至 {item.expected_end_date}</td><td>{item.status}</td><td>{item.result_version || "-"}</td><td><button onClick={() => act(() => choosePeriod(item))}>管理</button></td></tr>)}</tbody></table></section>}
    {currentPeriod && <section className="workflow"><h2>当前周期：{currentPeriod.name} · {currentPeriod.status}</h2><div className="actions wrap">{currentPeriod.status === "draft" && <button className="start" onClick={() => act(async () => { const created = await post(`/api/periods/${periodId}/start`, {}); await Promise.all([loadPeriods(), loadPapers()]); setMessage("周期已开始，纸表01已生成"); window.open(created.download_url, "_blank"); })}>开始周期并生成纸表01</button>}{currentPeriod.status === "active" && <button className="start" onClick={() => act(async () => { await post(`/api/periods/${periodId}/settle`, {}); await loadPeriods(); setMessage("已进入待结算；现在可以整表入账"); })}>公开申诉处理完成，进入待结算</button>}{currentPeriod.status !== "closed" && <button onClick={() => act(() => createReport("display", true))}>预览展示版草稿</button>}{currentPeriod.status === "settling" && <button className="danger" onClick={() => act(async () => { const closed = await post(`/api/periods/${periodId}/close`, {}); await Promise.all([loadPeriods(), loadResults()]); setMessage(`周期已关闭，正式结果版本 ${closed.result_version}`); })}>确认全部完成并关闭周期</button>}{currentPeriod.status === "closed" && <><button onClick={() => act(() => createReport("display", false))}>导出教室展示版</button><button onClick={() => act(() => createReport("teacher", false))}>导出教师存档版</button><button className="danger" onClick={() => act(async () => { const reason = window.prompt("请输入重新打开周期的原因"); if (!reason) return; await post(`/api/periods/${periodId}/reopen`, { reason }); await loadPeriods(); setMessage("周期已重新打开并保留审计原因"); })}>维护：重新打开</button></>}<button onClick={() => act(() => loadResults())}>刷新统计</button></div></section>}

    {previewRows.length > 0 && <section className="preview"><h2>名单预览（尚未写入）</h2><table><thead><tr><th>学号</th><th>姓名</th><th>组别</th><th>组长</th></tr></thead><tbody>{previewRows.map((row, index) => <tr key={index}><td>{row.student_number}</td><td>{row.name}</td><td>{row.group_number}组</td><td>{row.is_leader ? "是" : ""}</td></tr>)}</tbody></table></section>}
    {students.length > 0 && <section className="preview"><h2>当前名单（修改仅影响下一个周期）</h2><table><thead><tr><th>学号</th><th>姓名</th><th>组别</th><th>组长</th><th></th></tr></thead><tbody>{students.map((student, index) => <tr key={student.id}><td>{student.student_number}</td><td><input value={student.name} onChange={e => setStudents(students.map((item, i) => i === index ? { ...item, name:e.target.value } : item))}/></td><td><input type="number" min="1" max="20" value={student.group_number} onChange={e => setStudents(students.map((item, i) => i === index ? { ...item, group_number:String(e.target.value) } : item))}/></td><td><input type="checkbox" checked={Boolean(student.is_leader)} onChange={e => setStudents(students.map((item, i) => i === index ? { ...item, is_leader:e.target.checked } : item))}/></td><td><button onClick={() => act(async () => { const r = await fetch(`/api/projects/${selected}/students/${student.id}`, { method:"PUT", headers:{ "content-type":"application/json", "x-scoreflow-csrf":csrf }, body:JSON.stringify({ name:student.name, group_number:Number(student.group_number), is_leader:Boolean(student.is_leader) }) }); if (!r.ok) throw new Error((await r.json()).detail); await chooseProject(selected); setMessage("学生信息已保存"); })}>保存</button></td></tr>)}</tbody></table></section>}
    {papers.length > 0 && <section className="preview"><h2>纸表管理</h2>{currentPeriod?.status === "active" && <button onClick={() => act(async () => { const created = await post(`/api/periods/${periodId}/papers`, {}); await loadPapers(); window.open(created.download_url, "_blank"); })}>生成补充表</button>}<table><thead><tr><th>表号</th><th>正面</th><th>背面</th><th>状态</th><th>操作</th></tr></thead><tbody>{papers.map(paper => <tr key={paper.id}><td>{String(paper.sheet_number).padStart(2, "0")}</td><td>{paper.front_status} {paper.front_status === "missing" && <button onClick={() => act(async () => { await post(`/api/papers/${paper.id}/confirm-blank`, { side:"front" }); await loadPapers(); })}>确认空白</button>} {paper.front_status === "confirmed_blank" && <button onClick={() => act(() => withdrawBlank(paper.id, "front"))}>撤回空白</button>}</td><td>{paper.back_status} {paper.back_status === "missing" && <button onClick={() => act(async () => { await post(`/api/papers/${paper.id}/confirm-blank`, { side:"back" }); await loadPapers(); })}>确认空白</button>} {paper.back_status === "confirmed_blank" && <button onClick={() => act(() => withdrawBlank(paper.id, "back"))}>撤回空白</button>}</td><td>{paper.status}</td><td><a href={`/api/papers/${paper.id}/pdf`} target="_blank">下载</a> {paper.status === "issued" && paper.front_status === "missing" && paper.back_status === "missing" && <button onClick={() => act(async () => { await post(`/api/papers/${paper.id}/void-unused`, {}); await loadPapers(); })}>未使用作废</button>} {currentPeriod?.status === "settling" && paper.status === "issued" && sideReady(paper.front_status) && sideReady(paper.back_status) && <button className="start inline" onClick={() => act(async () => { await post(`/api/papers/${paper.id}/post`, { idempotency_key:crypto.randomUUID() }); await Promise.all([loadPapers(), loadResults()]); setMessage(`纸表${String(paper.sheet_number).padStart(2, "0")}已原子入账`); })}>整表入账</button>} {currentPeriod?.status === "settling" && paper.status === "posted" && <button className="danger inline" onClick={() => act(() => reversePaper(paper.id))}>撤销入账</button>}</td></tr>)}</tbody></table></section>}

    {selected && <section className="preview"><h2>扫描导入与复核</h2><p>支持多页 PDF、JPG、JPEG、PNG；推荐300dpi原文件。扫描不会自动入账。</p><input type="file" multiple accept=".pdf,.jpg,.jpeg,.png" onChange={e => setScanFiles(Array.from(e.target.files || []))}/><div className="actions"><button disabled={!scanFiles.length} onClick={() => act(uploadScans)}>导入并识别</button><button onClick={() => act(loadRuns)}>刷新结果</button></div>{jobs.map(job => <p key={job.id}>{job.stage} · {job.completed_pages}/{job.total_pages || "?"} 页 · {job.status} {!terminal.includes(job.status) && <button className="inline" onClick={() => act(() => cancelJob(job.id))}>取消</button>}</p>)}<table><thead><tr><th>文件/页</th><th>面别</th><th>状态</th><th>质量提示</th><th></th></tr></thead><tbody>{runs.map(run => <tr key={run.id}><td>{run.original_filename} / {run.page_index + 1}</td><td>{run.side || "待确认"}</td><td>{run.status}</td><td>{[...(run.quality?.problems || []), ...(run.version_conflict ? ["同一纸表面存在多个候选版本，请选择采用一个"] : [])].join("；") || "—"}</td><td>{run.status === "needs_identity" ? <button onClick={() => act(() => identify(run))}>输入短编号</button> : <button onClick={() => act(() => openReview(run.id))}>查看复核</button>}</td></tr>)}</tbody></table></section>}
    {review && <section className="preview review"><h2>疑点优先复核 · {review.side === "front" ? "正面" : "背面"}</h2><p><a href={`/api/recognition-runs/${review.id}/original`} target="_blank">查看原始文件</a> · <a href={`/api/recognition-runs/${review.id}/corrected`} target="_blank">查看完整校正图</a> · <a href={`/api/recognition-runs/${review.id}/notes-image`} target="_blank">查看纸面备注区</a> · 空白 {review.effective_counts?.blank || 0} · 斜线 {(review.effective_counts?.slash_forward || 0) + (review.effective_counts?.slash_back || 0)} · X {review.effective_counts?.x || 0} · 待复核 {review.effective_counts?.review || 0} · 预计影响 {review.effective_delta || 0} 分</p><button onClick={() => act(addNote)}>录入可选备注</button>{review.notes?.map((note:any) => <p key={note.id}>电子备注：{note.note_text}</p>)}<p>快捷键：1 空白、2 ／、3 ＼、4 X。点击图片可放大。</p>{review.observations.filter((item:any) => !item.manual_class && item.auto_class === "review").slice(0, 100).map((item:any) => <article key={item.slot_id}><a href={`/api/recognition-runs/${review.id}/slot/${item.slot_id}/image`} target="_blank"><img src={`/api/recognition-runs/${review.id}/slot/${item.slot_id}/image`}/></a><div>{item.student_number}号 {item.student_name}<br/>{item.rule_name} · 第{item.slot_index}格</div><div className="actions"><button onClick={() => decide(item.slot_id, "blank")}>空白</button><button onClick={() => decide(item.slot_id, "slash_forward")}>／</button><button onClick={() => decide(item.slot_id, "slash_back")}>＼</button><button onClick={() => decide(item.slot_id, "x")}>X</button></div></article>)}<button className="start" onClick={() => act(async () => { await post(`/api/recognition-runs/${review.id}/adopt`, {}); await Promise.all([loadRuns(), loadPapers()]); setReview(null); setMessage("该面复核结果已采用，尚未入账"); })}>采用该面复核结果</button></section>}
    {results && <section className="results"><h2>周期结果 · {results.period.status === "closed" ? `正式版本 ${results.period.result_version}` : "结算中/未最终确认"}</h2><h3>小组排名</h3><table><thead><tr><th>排名</th><th>小组</th><th>人数</th><th>总分</th><th>平均分</th></tr></thead><tbody>{results.groups.map((group:any) => <tr key={group.group_number}><td>{group.rank}</td><td>{group.group_number}组</td><td>{group.member_count}</td><td>{group.total_score}</td><td>{group.average_score.toFixed(2)}</td></tr>)}</tbody></table><h3>个人结果</h3><table><thead><tr><th>学号</th><th>姓名</th><th>小组</th><th>加分</th><th>扣分</th><th>总分</th></tr></thead><tbody>{results.students.map((student:any) => <tr key={student.student_id}><td>{student.student_number}</td><td>{student.name}</td><td>{student.group_number}组</td><td>{student.positive_score}</td><td>{student.negative_score}</td><td>{student.total_score}</td></tr>)}</tbody></table><h3>项目统计</h3><table><thead><tr><th>项目</th><th>单位分值</th><th>有效次数</th><th>合计</th></tr></thead><tbody>{results.rules.map((rule:any) => <tr key={rule.rule_id}><td>{rule.name}</td><td>{rule.unit_score}</td><td>{rule.mark_count}</td><td>{rule.amount}</td></tr>)}</tbody></table><h3>账本与扫描证据</h3><table><thead><tr><th>表号</th><th>学生</th><th>项目</th><th>次数</th><th>金额</th><th>性质</th><th>证据</th></tr></thead><tbody>{results.ledger.map((entry:any) => <tr key={entry.id}><td>{String(entry.sheet_number).padStart(2, "0")}</td><td>{entry.student_number} {entry.name}</td><td>{entry.rule_name}</td><td>{entry.mark_count}</td><td>{entry.amount}</td><td>{entry.source_entry_id ? "撤销流水" : "入账流水"}</td><td>{entry.run_id ? <a href={`/api/recognition-runs/${entry.run_id}/corrected`} target="_blank">校正图 · {entry.slot_ids.length}槽</a> : "空白确认"}</td></tr>)}</tbody></table></section>}
  </main>;
}

createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);
